Add a vite.config.js file
CaptainCodex/gra pull request #25
Opened 2023-12-11 07:17 UTC by CaptainCodex

- Add the vite react plugin to the config
- Add yarn scripts commands to package.json `vite:dev` and `vite:build`

2023-12-11 07:22 UTC, CaptainCodex commented
Add `vite-plugin-react` package. #

2023-12-11 07:24 UTC, CaptainCodex commented
Add `vite-plugin-react` package.

2023-12-11 07:35 UTC, GrantDawsonAssistant commented
Can we add `vite-plugin-react` package.

2023-12-11 07:37 UTC, GrantDawsonAssistant requested changes
Add `vite-plugin-react` package.

2023-12-11 08:02 UTC, GrantDawsonAssistant reviewed
Review comment

2023-12-11 08:03 UTC, GrantDawsonAssistant commented
> Review comment

this reply

2023-12-11 08:44 UTC, GrantDawsonAssistant requested changes
revert file

2023-12-11 08:45 UTC, GrantDawsonAssistant reviewed
review comment 2

2023-12-11 08:52 UTC, GrantDawsonAssistant requested changes
this should be changed

2023-12-11 08:54 UTC, GrantDawsonAssistant requested changes

2023-12-11 08:54 UTC, GrantDawsonAssistant commented on package.json
> +    "vite-plugin-react": "^1.0.0"
highlighted code

2023-12-11 08:54 UTC, GrantDawsonAssistant commented on package.json
> +    "vite-plugin-react": "^1.0.0"
conversing

2023-12-11 20:42 UTC, CaptainCodex commented on package.json
> -    "vite": "^5.0.2"
hi

2023-12-11 20:42 UTC, CaptainCodex reviewed
lo

2023-12-11 21:59 UTC, GrantDawsonAssistant requested changes

2023-12-11 21:59 UTC, GrantDawsonAssistant commented on package.json
>    },
pop

2023-12-12 06:04 UTC, GrantDawsonAssistant commented
> this should be changed (edit 3)

2023-12-16 06:30 UTC, closed without merging